/* Generated by tools/update_preview.py. Uses only the local demo transport. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const clamp = (n, lo, hi) => Math.min(hi, Math.max(lo, n));
  let snapshot = {values: {}, modules: {}, events: [], transport: {}};
  let connected = false, lastMessage = 0, retry = 250, ws;
  let commandSeq = 0, testRequested = false, lastControlResult = '';
  const commands = new Map();
  const history = [];
  const absent = {value: null, quality: 'unavailable'};
  const qualityNames = {live: 'Live', stale: 'Stale', unavailable: 'No signal', fault: 'Fault'};
  const instrumentCards = [...document.querySelectorAll('[data-signal]')];
  const moduleNames = {taillights: 'LIGHTING', comfort: 'COMFORT', watermeth: 'WATER / METH', knock: 'KNOCK'};
  for (const [name, label] of Object.entries(moduleNames)) {
    const tag = document.createElement('span'); tag.className = 'module-tag'; tag.dataset.module = name;
    const title = document.createElement('span'); title.textContent = label;
    const state = document.createElement('b'); state.textContent = 'No signal';
    tag.append(title, state); $('module-strip').append(tag);
  }
  function signal(key) {
    const v = snapshot.values[key] || absent;
    return connected ? v : {...v, quality: v.value === null ? 'unavailable' : 'stale'};
  }
  function live(key) { const v = signal(key); return v.quality === 'live' ? v.value : null; }
  function display(id, key, digits = 0, convert = v => v) {
    const el = $(id), v = signal(key);
    el.dataset.quality = v.quality;
    el.title = `${key}: ${v.quality}`;
    const value = v.quality === 'live' ? convert(v.value) : null;
    el.textContent = value === null ? '—' :
      typeof value === 'number' ? value.toFixed(digits) : value;
    return value;
  }
  function bar(id, value, min, max) {
    $(id).style.width = `${value === null ? 0 : clamp((value - min) / (max - min) * 100, 0, 100)}%`;
  }
  function render() {
    window.dispatchEvent(new CustomEvent('frogdash-state', {detail: {snapshot, connected}}));
    const replay = snapshot.mode === 'replay';
    const demo = snapshot.mode === 'demo';
    $('connection').textContent = !connected ? 'DISCONNECTED — reconnecting' :
      `${demo ? 'DEMO — simulated data' : replay ? 'REPLAY — recorded data' : 'CAN'} · ${snapshot.transport.status || 'waiting'}`;
    const sourceState = !connected || !snapshot.transport.connected ? 'offline' : demo ? 'demo' : replay ? 'replay' : 'live';
    $('connection-summary').dataset.state = sourceState;
    $('connection-summary').textContent = sourceState === 'live' ? 'LIVE CAN' : sourceState === 'demo' ? 'DEMO · SIMULATED' : sourceState === 'replay' ? 'REPLAY · RECORDED' : connected ? 'CAN OFFLINE' : 'DISCONNECTED';
    if (demo && sourceState === 'offline') $('connection-summary').textContent = 'DEMO · OFFLINE';
    const recording = snapshot.recording || {state: 'disabled'};
    const recordingState = !connected ? 'unknown' : recording.state;
    $('recording-badge').dataset.state = recordingState;
    $('recording-badge').textContent = demo ? 'LOG DEMO' : recordingState === 'recording' ? `REC ${recording.hz} Hz` : recordingState === 'error' ? 'LOG ERROR' : recordingState === 'disabled' ? 'LOG OFF' : 'LOG WAIT';
    $('recording-badge').title = recording.error || recording.file || 'MLG recording status';
    $('log-status').textContent = demo ? 'Preview only — no files are recorded here.' : !connected ? 'Connection lost — recording status unknown.' :
      recordingState === 'recording' ? `${recording.file} · ${recording.rows} samples · ${recording.dropped} dropped` :
      recordingState === 'error' ? `Recording paused: ${recording.error}` : recordingState === 'disabled' ? 'Recording disabled. Enable a log directory in the service configuration.' : 'Waiting for recorder';
    // Module status lives under Sensors; flag the Sensors icon when any module is not live.
    $('diagnostics-launch').dataset.warning = String([...$('module-strip').children].some(tag => tag.dataset.quality && tag.dataset.quality !== 'live'));
    for (const tag of $('module-strip').children) {
      const quality = connected ? (snapshot.modules[tag.dataset.module] || 'unavailable') : 'stale';
      tag.dataset.quality = quality;
      tag.querySelector('b').textContent = quality === 'live' ? 'Online' : quality === 'stale' ? 'Offline' : 'No signal';
    }
    for (const card of instrumentCards) {
      const v = signal(card.dataset.signal);
      card.dataset.quality = v.quality;
      const label = card.querySelector('.quality-label');
      if (label) label.textContent = qualityNames[v.quality] || v.quality;
    }
    $('source-health').textContent = Object.entries(snapshot.modules).map(([k, v]) => `${k.toUpperCase()} ${connected ? v : 'stale'}`).join(' · ');
    if (snapshot.gps) $('connection').textContent += ` · ${snapshot.gps.status} · GPS TX: ${snapshot.gps.tx_status}`;
    const rpm = display('rpm-value', 'engine.rpm');
    $('rpm-bar-fill').setAttribute('stroke-dasharray', `${rpm === null ? 0 : clamp(rpm / 7000 * 100, 0, 100)} 100`);
    document.querySelector('.tach').dataset.tone = rpm !== null && rpm >= 6000 ? 'danger' : 'normal';
    display('speed-digits', 'vehicle.speed_kph', 0, window.FrogdashUnits.distance);
    document.body.dataset.speedLive = live('vehicle.speed_kph') !== null;
    $('gps-sats').textContent = live('vehicle.speed_kph') === null ? 'GPS · NO LIVE FIX' :
      `GPS SPEED${live('gps.satellites') === null ? '' : ' · ' + live('gps.satellites') + ' SAT'}`;
    const temp = window.FrogdashUnits.temperature;
    bar('coolant-fill', display('coolant-val', 'engine.coolant_c', 0, temp), temp((100 - 32) / 1.8), temp((250 - 32) / 1.8));
    document.querySelector('[data-signal="engine.coolant_c"]').dataset.tone = live('engine.coolant_c') !== null && live('engine.coolant_c') >= (snapshot.drive?.settings?.coolant_c ?? 112) ? 'danger' : 'normal';
    bar('iat-fill', display('iat-val', 'engine.iat_c', 0, temp), temp(-32 / 1.8), temp(168 / 1.8));
    bar('fuel-fill', display('fuel-val', 'vehicle.fuel_pct'), 0, 100);
    display('boost-val', 'engine.boost_kpa', 1, window.FrogdashUnits.boost);
    const boost = live('engine.boost_kpa') === null ? null : live('engine.boost_kpa') * .145037738;
    const boostPosition = boost === null ? 100 / 3 : clamp((boost + 15) / 45 * 100, 0, 100);
    $('boost-fill').style.left = `${Math.min(100 / 3, boostPosition)}%`;
    $('boost-fill').style.width = `${Math.abs(boostPosition - 100 / 3)}%`;
    $('boost-fill').style.background = boost !== null && boost < 0 ? 'var(--blue)' : 'var(--accent)';
    $('boost-state').textContent = boost === null ? qualityNames[signal('engine.boost_kpa').quality] : boost < 0 ? 'VACUUM' : 'BOOST';
    bar('batt-fill', display('batt-val', 'vehicle.battery_v', 1), 10, 16);
    bar('fuelp-fill', display('fuelp-val', 'engine.fuel_pressure_psi', 1, window.FrogdashUnits.pressure), 0, window.FrogdashUnits.pressure(100));
    bar('oilp-fill', display('oilp-val', 'engine.oil_pressure_psi', 1, window.FrogdashUnits.pressure), 0, window.FrogdashUnits.pressure(100));
    display('ego-val', 'engine.ego_correction_pct', 1, n => n - 100);
    const afr = display('afr-val', 'engine.afr', 1);
    $('afr-lambda').textContent = afr === null ? '—' : (afr / 14.7).toFixed(2);
    const target = display('afr-target', 'ecu.afr_target', 1);
    $('afr-state').textContent = afr === null ? qualityNames[signal('engine.afr').quality] : target === null ? 'Target unavailable' :
      Math.abs(afr - target) < .25 ? 'At target' : afr < target ? 'Below target' : 'Above target';
    $('afr-pointer').hidden = afr === null;
    if (afr !== null) $('afr-pointer').style.left = `${clamp((afr - 10) / 8 * 100, 0, 100)}%`;
    $('afr-target-marker').hidden = target === null;
    if (target !== null) $('afr-target-marker').style.left = `${clamp((target - 10) / 8 * 100, 0, 100)}%`;
    display('meth-state-pill', 'meth.state');
    $('meth-state-pill').dataset.state = live('meth.state') || 'UNKNOWN';
    display('meth-duty-val', 'meth.duty_pct');
    display('meth-tank-val', 'meth.tank_pct');
    display('meth-flow-pill', 'meth.flow');
    $('meth-flow-pill').dataset.flow = live('meth.flow') || 'UNKNOWN';
    const flags = live('meth.fault_flags');
    $('meth-faults').textContent = flags ? 'FAULT' : '';
    for (const side of ['left', 'right']) {
      const v = signal(`lighting.turn_${side}`);
      $(`turn-${side}`).dataset.on = connected && v.quality === 'live' && v.value ? 'true' : 'false';
      $(`turn-${side}`).title = `Turn signal: ${v.quality}`;
    }
    $('icon-highbeam').dataset.quality = 'unavailable';
    $('icon-highbeam').title = 'High beam source unavailable';
    for (const name of ['brake', 'running', 'reverse']) {
      const v = signal(`lighting.${name}`), icon = $(`icon-${name}`);
      icon.classList.toggle('on', v.quality === 'live' && v.value === true);
      icon.dataset.quality = v.quality;
      icon.title = `${name}: ${v.quality === 'live' ? v.value ? 'ON' : 'OFF' : v.quality}`;
    }
    const warnings = [];
    if (!connected) warnings.push('DATA CONNECTION LOST');
    else if (!snapshot.transport.connected) warnings.push('CAN OFFLINE');
    if (snapshot.gps?.conflict) warnings.push('GPS TRANSMITTER CONFLICT');
    if (snapshot.drive) warnings.push(...snapshot.drive.alerts.filter(a => a.active || a.latched).map(a => a.title));
    else {
      if (live('knock.critical')) warnings.push('KNOCK CRITICAL');
      else if (live('knock.warning')) warnings.push('KNOCK WARNING');
      if (flags || live('meth.state') === 'FAULT') warnings.push('WATER/METH FAULT');
      if (live('engine.coolant_c') !== null && live('engine.coolant_c') >= 112) warnings.push('COOLANT HIGH');
    }
    const bad = Object.entries(snapshot.values).filter(([key, v]) => !key.startsWith('race.') && v.quality === 'fault').length;
    if (bad) warnings.push('SENSOR FAULT');
    $('warn-banner').hidden = warnings.length === 0;
    $('warn-banner').textContent = warnings.join(' · ');
    if ($('knock-overlay').open) renderKnock();
    renderControls();
    if ($('diagnostics').open) renderDiagnostics();
    window.frogdashRendered = (window.frogdashRendered || 0) + 1;
    updateUnits();
    window.FrogdashInstruments?.render(snapshot, connected);
  }

  function updateUnits() {
    const u = window.FrogdashUnits;
    document.querySelector('.speed-readout .unit').textContent = u.speedUnit;
    for (const [selector, unit, scales] of [
      ['.boost-gauge', u.metric ? 'kPa' : 'psi', [-15,0,15,30].map(u.pressure)],
      ['[data-signal="engine.coolant_c"]', u.metric ? '\u00b0C' : '\u00b0F', [u.temperature((100-32)/1.8),u.temperature((250-32)/1.8)]],
      ['[data-signal="engine.iat_c"]', u.metric ? '\u00b0C' : '\u00b0F', [u.temperature(-32/1.8),u.temperature(168/1.8)]],
      ['[data-signal="engine.oil_pressure_psi"]', u.metric ? 'kPa' : 'psi', [0,u.pressure(100)]],
      ['[data-signal="engine.fuel_pressure_psi"]', u.metric ? 'kPa' : 'psi', [0,u.pressure(100)]]
    ]) { const card = document.querySelector(selector); card.querySelector('.unit').textContent = unit; [...card.querySelectorAll('.scale-labels span')].forEach((n,i) => n.textContent = Math.round(scales[i])); }
  }
  function renderKnock() {
    const energy = display('knock-energy-num', 'knock.energy');
    display('knock-baseline-num', 'knock.baseline');
    const threshold = display('knock-threshold-num', 'knock.threshold');
    display('knock-events-num', 'knock.event_count');
    display('knock-last-rpm', 'knock.last_rpm');
    display('knock-last-boost', 'knock.last_boost_kpa', 0, n => `${n} kPa`);
    $('knock-headroom-num').textContent = energy === null || threshold === null ? '—' : threshold - energy;
    $('knock-status').textContent = energy === null ? signal('knock.energy').quality.toUpperCase() :
      live('knock.critical') ? 'CRITICAL' : live('knock.warning') ? 'WARNING' : !live('knock.learned') ? 'LEARNING' : 'OK';
    $('knock-status').dataset.status = $('knock-status').textContent;
    $('knock-source').textContent = `${snapshot.mode === 'demo' ? 'SIMULATED' : snapshot.mode === 'replay' ? 'REPLAY' : 'KNOCK SENSOR'} · ${qualityNames[signal('knock.energy').quality].toUpperCase()}`;
    const now = performance.now();
    while (history.length && history[0].at < now - 6700) history.shift();
    const y = n => 270 - clamp(n, 0, 255) / 255 * 252;
    function path(key) {
      let d = '', pen = false;
      for (const p of history) {
        if (p[key] === null) { pen = false; continue; }
        const x = 936 - (now - p.at) / 6700 * 888;
        d += `${pen ? 'L' : 'M'}${x.toFixed(1)},${y(p[key]).toFixed(1)} `;
        pen = true;
      }
      return d;
    }
    $('knock-energy').setAttribute('d', path('energy'));
    $('knock-baseline').setAttribute('d', path('baseline'));
    $('knock-thresh').setAttribute('visibility', threshold === null ? 'hidden' : 'visible');
    $('knock-thresh').setAttribute('y1', y(threshold || 0));
    $('knock-thresh').setAttribute('y2', y(threshold || 0));
    $('knock-thresh-label').textContent = threshold === null ? '' : `THRESHOLD ${threshold}`;
    $('knock-thresh-label').setAttribute('y', Math.max(30, y(threshold || 0) - 7));
    $('knock-danger-zone').setAttribute('height', threshold === null ? 0 : y(threshold) - 18);
    $('knock-current-dot').setAttribute('visibility', energy === null ? 'hidden' : 'visible');
    $('knock-current-dot').setAttribute('cy', y(energy || 0));
    const samples = history.filter(p => p.energy !== null);
    $('knock-peak').textContent = samples.length ? Math.max(...samples.map(p => p.energy)) : '—';
  }

  function renderDiagnostics() {
    $('module-health').textContent = $('source-health').textContent + ` · ${snapshot.transport.received || 0} received · ${snapshot.transport.malformed || 0} malformed`;
    const filter = $('signal-filter').value.toLowerCase().trim();
    $('signals').replaceChildren(...Object.keys(snapshot.values).filter(key => key.toLowerCase().includes(filter)).sort().map(key => {
      const v = signal(key), row = document.createElement('tr');
      row.dataset.quality = v.quality;
      const reading = typeof v.value === 'number' ? Number(v.value.toFixed(3)) : v.value;
      for (const text of [key, reading ?? '—', qualityNames[v.quality], v.source || (v.source_id == null ? '—' : `0x${v.source_id.toString(16).toUpperCase()}`)]) {
        const cell = document.createElement('td'); cell.textContent = text; row.append(cell);
      }
      return row;
    }));
    $('fault-history').textContent = snapshot.events.slice(-15).map(e => `${new Date(e.timestamp_ms).toLocaleTimeString()} 0x${e.id.toString(16).toUpperCase()} ${JSON.stringify(e.values)}`).join('\n') || 'No events received';
  }
  function disconnect() {
    connected = false;
    if (commands.size) {
      $('command-result').textContent = 'Connection lost; command outcome unknown. Check live telemetry after reconnect.';
      $('command-result').dataset.status = 'unknown';
    }
    for (const timer of commands.values()) clearTimeout(timer);
    commands.clear(); testRequested = false;
    history.length = 0;
    render();
  }
  function connect() {
    ws = new FrogdashDemoSocket(`${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}/state`);
    ws.onmessage = event => {
      try {
        const next = JSON.parse(event.data);
        if (next.type === 'command_result') {
          clearTimeout(commands.get(next.request_id)); commands.delete(next.request_id);
          $('command-result').textContent = `${next.status.toUpperCase()}: ${next.message}`;
          $('command-result').dataset.status = next.status;
          renderControls();
          return;
        }
        if (next.type !== 'state' || !next.values || !next.transport) return;
        snapshot = next; connected = true; lastMessage = performance.now(); retry = 250;
        history.push({at: lastMessage, energy: live('knock.energy'), baseline: live('knock.baseline')});
        render();
      } catch { ws.close(); }
    };
    ws.onerror = () => ws.close();
    ws.onclose = () => { disconnect(); setTimeout(connect, retry); retry = Math.min(retry * 2, 5000); };
  }
  let logsPending = false;
  async function loadLogs() {
    if (logsPending) return;
    if (snapshot.mode === 'demo' || !snapshot.recording?.enabled) { $('log-files').replaceChildren(); return; }
    logsPending = true;
    try {
      const response = await fetch('/logs', {signal: AbortSignal.timeout(3000)});
      if (!response.ok) throw new Error('Could not list logs');
      const listing = await response.json();
      $('log-files').replaceChildren(...listing.files.map(file => {
        const item = document.createElement('li');
        const name = document.createElement(file.active ? 'span' : 'a');
        name.textContent = file.name;
        if (!file.active) { name.href = `/logs/${encodeURIComponent(file.name)}`; name.download = file.name; }
        const size = document.createElement('span');
        size.textContent = `${(file.bytes / 1048576).toFixed(1)} MiB${file.active ? ' · Recording — available after rotation' : ''}`;
        item.append(name, size); return item;
      }));
      if (!listing.files.length) $('log-files').textContent = 'No saved logs yet.';
    } catch { $('log-files').textContent = 'Log list unavailable. Try Refresh files.'; }
    finally { logsPending = false; }
  }
  $('refresh-logs').onclick = loadLogs;
  $('diagnostics-launch').onclick = () => { $('diagnostics').showModal(); renderDiagnostics(); loadLogs(); };
  $('diagnostics-close').onclick = () => $('diagnostics').close();
  $('signal-filter').addEventListener('input', renderDiagnostics);
  function renderControls() {
    const controls = snapshot.controls || {reasons: {}};
    $('control-connection').textContent = !connected ? 'Disconnected — controls unavailable' :
      snapshot.mode === 'demo' ? 'DEMO — simulated controls, no vehicle connection' : snapshot.mode === 'replay' ? 'REPLAY — controls unavailable' : !snapshot.transport.connected ? 'CAN offline — controls unavailable' : 'Connected to vehicle controllers';
    for (const button of document.querySelectorAll('[data-action]')) {
      const action = button.dataset.action;
      const disarm = action === 'meth.arm' && button.dataset.value === '0';
      const stop = disarm || action === 'meth.stop';
      const reason = controls.reasons[disarm ? 'meth.disarm' : action];
      button.disabled = !connected || snapshot.mode === 'replay' || !!reason || (!stop && commands.size > 0);
      button.title = reason || '';
    }
    const text = key => live(key) ?? '—';
    $('meth-live-summary').textContent = `${text('meth.state')} · Pump ${text('meth.duty_pct')}% · Tank ${text('meth.tank_pct')}% · Flow ${text('meth.flow')}`;
    $('meth-control-reason').textContent = controls.reasons['meth.arm'] || controls.reasons['meth.boost'] || 'Ready for commands. Live state updates from the module.';
    $('test-control-reason').textContent = controls.test_active ? 'Pump test active — stops automatically after 3 seconds.' :
      controls.reasons['meth.test'] || 'Test ready. Closing this panel or losing the connection stops the test.';
    const knockEnabled = live('knock.enabled');
    $('knock-live-summary').textContent = `${knockEnabled === null ? 'No live status' : knockEnabled ? 'Enabled' : 'Disabled'} · Offset ${text('knock.config.threshold_offset')} · Multiplier ${text('knock.config.multiplier')}`;
    $('lighting-live-summary').textContent = `Applied brightness ${text('lighting.brightness')} / 255 · Left ${text('lighting.left_state')} · Right ${text('lighting.right_state')}`;
    const result = JSON.stringify(controls.last_result || null);
    if (result !== lastControlResult && controls.last_result) {
      lastControlResult = result;
      $('command-result').textContent = `${controls.last_result.status.toUpperCase()}: ${controls.last_result.message}`;
      $('command-result').dataset.status = controls.last_result.status;
    }
  }
  function sendCommand(action, value) {
    if (!connected || ws.readyState !== FrogdashDemoSocket.OPEN) return;
    const request_id = `${Date.now()}-${++commandSeq}`;
    const message = {type: 'command', request_id, action};
    if (value !== undefined) message.value = value;
    commands.set(request_id, setTimeout(() => {
      commands.delete(request_id);
      $('command-result').textContent = 'No response — outcome unknown. Check live telemetry before trying again.';
      $('command-result').dataset.status = 'unknown';
      renderControls();
    }, 3000));
    if (action === 'meth.test') testRequested = true;
    if (action === 'meth.stop' || (action === 'meth.arm' && value === 0)) testRequested = false;
    $('command-result').textContent = 'Sending command; waiting for controller…';
    $('command-result').dataset.status = 'pending';
    ws.send(JSON.stringify(message)); renderControls();
  }
  window.FrogdashControls = {send: sendCommand};
  for (const button of document.querySelectorAll('[data-action]')) {
    if (button.dataset.compute !== undefined) continue; // Owner computes the value and calls send().
    button.onclick = () => {
      let value;
      if (button.dataset.input) {
        const input = $(button.dataset.input);
        if (!input.reportValidity() || input.value === '') return;
        value = Number(input.value);
        if (button.dataset.scale) value = Math.round(value * Number(button.dataset.scale));
      } else if (button.dataset.value !== undefined) value = Number(button.dataset.value);
      sendCommand(button.dataset.action, value);
    };
  }
  function stopLocalTest() {
    if (testRequested) sendCommand('meth.stop');
    testRequested = false;
  }
  function selectControlTab(name) {
    if (name !== 'meth') stopLocalTest();
    for (const button of document.querySelectorAll('[data-tab]')) {
      const active = button.dataset.tab === name;
      button.setAttribute('aria-selected', String(active)); button.tabIndex = active ? 0 : -1;
      $(`panel-${button.dataset.tab}`).hidden = !active;
    }
    document.querySelector('.control-panels').scrollTop = 0;
    if (name === 'wifi') loadWifi();
  }
  let wifiBusy = false, demoWifi = false;
  function renderWifi(status) {
    const demo = snapshot.mode === 'demo';
    $('wifi-summary').textContent = demo ? `DEMO · Hotspot ${status.enabled ? 'on' : 'off'}` : status.enabled ? `Hotspot on · ${Math.ceil(status.remaining_seconds / 60)} minutes remaining` : 'Hotspot off';
    $('wifi-ssid').textContent = status.ssid || '—';
    $('wifi-password').textContent = status.enabled ? status.password || '—' : '—';
    $('wifi-url').textContent = status.enabled ? status.url || '—' : '—';
    $('wifi-code').textContent = status.enabled ? status.access_code || '—' : '—';
    $('wifi-feedback').textContent = status.error || (demo ? 'Preview only — no Wi-Fi network is created.' : status.configured ? 'Ready. Access switches off automatically after 20 minutes.' : 'Configure the Pi Wi-Fi helper to enable hotspot access.');
    $('wifi-on').disabled = wifiBusy || !status.configured || status.enabled;
    $('wifi-off').disabled = wifiBusy || !status.configured || !status.enabled;
  }
  async function loadWifi(enabled) {
    if (wifiBusy) return;
    if (snapshot.mode === 'demo') {
      if (enabled !== undefined) demoWifi = enabled;
      renderWifi({configured: true, enabled: demoWifi, ssid: 'Frogdash (preview)', password: 'Preview only', url: 'Available on the Pi', access_code: '12345678'});
      return;
    }
    wifiBusy = true; $('wifi-on').disabled = $('wifi-off').disabled = true;
    if (enabled !== undefined) $('wifi-feedback').textContent = 'Updating hotspot…';
    try {
      const options = enabled === undefined ? {} : {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({enabled})};
      const response = await fetch('/connectivity', {...options, signal: AbortSignal.timeout(28000)});
      if (!response.ok) throw new Error('Could not update Wi-Fi. Check the Pi hotspot service.');
      const status = await response.json(); wifiBusy = false; renderWifi(status);
    } catch (error) { wifiBusy = false; renderWifi({configured: false, enabled: false, error: error.message}); }
  }
  $('wifi-on').onclick = () => loadWifi(true);
  $('wifi-off').onclick = () => loadWifi(false);
  setInterval(() => { if ($('controls-dialog').open && !$('panel-wifi').hidden) loadWifi(); }, 3000);
  for (const tab of document.querySelectorAll('[data-tab]')) {
    tab.onclick = () => selectControlTab(tab.dataset.tab);
    tab.onkeydown = event => {
      const tabs = [...document.querySelectorAll('[data-tab]')];
      let index = tabs.indexOf(tab);
      if (event.key === 'ArrowDown') index = (index + 1) % tabs.length;
      else if (event.key === 'ArrowUp') index = (index + tabs.length - 1) % tabs.length;
      else if (event.key === 'Home') index = 0;
      else if (event.key === 'End') index = tabs.length - 1;
      else return;
      event.preventDefault(); selectControlTab(tabs[index].dataset.tab); tabs[index].focus();
    };
  }
  $('controls-launch').onclick = () => { $('controls-dialog').showModal(); renderControls(); };
  $('meth-cell').onclick = () => { selectControlTab('meth'); $('controls-launch').click(); };
  $('controls-close').onclick = () => $('controls-dialog').close();
  $('controls-dialog').addEventListener('close', stopLocalTest);
  document.addEventListener('visibilitychange', () => { if (document.hidden) stopLocalTest(); });
  window.addEventListener('pagehide', stopLocalTest);
  $('knock-launch').onclick = () => { $('knock-overlay').showModal(); renderKnock(); };
  $('knock-close').onclick = () => $('knock-overlay').close();
  document.addEventListener('keydown', event => {
    if (event.target.matches('input, textarea, select')) return;
    if (document.querySelector('dialog[open]')) return;
    if (event.key.toLowerCase() === 'm') $('controls-launch').click();
    if (event.key.toLowerCase() === 'k') $('knock-launch').click();
  });
  setInterval(() => {
    const date = new Date();
    $('clock-time').textContent = date.toLocaleTimeString([], {hour: 'numeric', minute: '2-digit', hour12: true});
    $('clock-tz').textContent = '';
    if (connected && performance.now() - lastMessage > 1500) { disconnect(); ws.close(); }
  }, 250);
  let rawPending = false;
  setInterval(async () => {
    if (!$('diagnostics').open || rawPending) return;
    if (snapshot.mode === 'demo') { $('raw-frames').textContent = 'Demo mode — no CAN connection.'; return; }
    rawPending = true;
    try {
      const result = await fetch('/raw', {signal: AbortSignal.timeout(1500)});
      const frames = await result.json();
      $('raw-frames').textContent = frames.map(f => `${f.extended ? 'EXT' : f.error ? 'ERR' : 'STD'} ${f.id.toString(16).toUpperCase()}#${f.data} ${f.remote ? 'RTR' : ''}`).join('\n');
    } catch { $('raw-frames').textContent = 'Raw traffic unavailable'; }
    finally { rawPending = false; }
  }, 1000);
  render(); connect();
})();
