"""Copy the authoritative UI into the standalone, explicitly simulated preview.

Run after editing hardware/ui. --check verifies committed preview assets match.
The production service never loads the demo transport.
"""
import argparse
from hashlib import sha256
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def assets():
    source = ROOT / 'hardware' / 'ui'
    html = (source / 'index.html').read_text(encoding='utf-8')
    html = html.replace('Frogdash · Driver display', 'Frogdash · Simulated design preview')
    html = html.replace('<script src="app.js"></script>', '<script src="demo.js"></script>\n<script src="app.js"></script>')
    js = (source / 'app.js').read_text(encoding='utf-8')
    js = js.replace('/* Production client: values come exclusively from the local state service. */',
                    '/* Generated by tools/update_preview.py. Uses only the local demo transport. */')
    assert js.count('new WebSocket(') == 1
    js = js.replace('new WebSocket(', 'new FrogdashDemoSocket(')
    js = js.replace('WebSocket.OPEN', 'FrogdashDemoSocket.OPEN')
    css = (source / 'style.css').read_text(encoding='utf-8')
    css += '\n/* Preview-only playback controls. */\n.demo-playback { display:flex; gap:6px; }\n.demo-control { min-height:40px; padding:7px 11px; border:1px solid var(--line); border-radius:6px; background:var(--raised); color:var(--text); font-size:13px; font-weight:750; }\n.demo-control[aria-pressed=true] { border-color:var(--accent); color:var(--accent); }\n'
    demo = (ROOT / 'preview' / 'demo.js').read_text(encoding='utf-8')
    personalize = (source / 'personalize.js').read_text(encoding='utf-8')
    extra = {name: (source / name).read_text(encoding='utf-8') for name in ('viewport.js', 'responsive.css', 'instruments.js', 'instruments.css', 'navigation.js', 'driving.js', 'trip.js', 'operations.js', 'units.js', 'review.js', 'review.css', 'camera.js', 'camera.css')}
    # A published HTML update must not reuse cached CSS/JS from the previous design.
    for name, content in [('style.css', css), ('app.js', js), ('demo.js', demo), ('personalize.js', personalize), *extra.items()]:
        version = sha256(content.encode('utf-8')).hexdigest()[:12]
        html = html.replace(f'"{name}"', f'"{name}?v={version}"')
    return {'index.html': html, 'style.css': css, 'app.js': js, 'personalize.js': personalize, **extra}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in assets().items():
        dest = ROOT / 'preview' / name
        if args.check:
            if dest.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Preview is out of date: {name}. Run python tools/update_preview.py')
        else:
            dest.write_text(content, encoding='utf-8', newline='\n')
    print('Preview assets match the production design.' if args.check else 'Updated standalone preview assets.')
